#!/bin/bash
patch_project=`pwd`;
patch_install=$1;

echo "#!/bin/bash
python3 $patch_project/anagram.py -d $patch_projec/output.json \$@"  >> "$patch_project/run"

`ln -s $patch_project/run $patch_install/anagram`

echo "[!] installation was a success!"

